language: haxe

haxe:
- development
- stable

before_install:
- haxelib git medic https://github.com/wartman/medic --always
- haxelib install hxnodejs --always

- sudo apt-get install -y php7.2

script:
- haxe test-nodejs.hxml
- node dist/node/index.js

- haxe test-php.hxml
- php dist/php/index.php
